actors:
  becolomochi:
    image_url: /images/actors/becolomochi.jpg
    name: becolomochi
    url: http://twitter.com/becolomochi
  curry:
    image_url: /images/actors/curry.png
    name: curry
    url: http://twitter.com/becolomochi
author: becolomochi
description: べこと旦那がゆるく話すべころもちチャンネル
description_long: べこ(becolomochi)と旦那が日々のことなどをゆるく話すポッドキャストで、べころもちチャンネルの略
email: becolomochi.channel@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-125086659-1
hashtag: becochan
itunes_podcast_url: https://itunes.apple.com/jp/podcast/becochan/id1440381293
keywords: manga,anime,daily,becolomochi
language: ja
markdown: kramdown
permalink: /:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: becochan
url: https://channel.becolomochi.com
